package com.example.hyarpg.utils;

public enum StatType {

    /* Primary Resources */
    LIFE_FLAT,
    LIFE_PERCENT,

    LIFE_REGEN_FLAT,
    LIFE_REGEN_PERCENT,

    STAMINA_FLAT,
    STAMINA_PERCENT,

    STAMINA_REGEN_FLAT,
    STAMINA_REGEN_PERCENT,

    MANA_FLAT,
    MANA_PERCENT,

    MANA_REGEN_FLAT,
    MANA_REGEN_PERCENT,

    /* Damage */
    FIRE_DAMAGE_FLAT,
    FIRE_DAMAGE_PERCENT,

    COLD_DAMAGE_FLAT,
    COLD_DAMAGE_PERCENT,

    LIGHTNING_DAMAGE_FLAT,
    LIGHTNING_DAMAGE_PERCENT,

    POISON_DAMAGE_FLAT,
    POISON_DAMAGE_PERCENT,

    PHYSICAL_DAMAGE_FLAT,
    PHYSICAL_DAMAGE_PERCENT,

    MAGICAL_DAMAGE_FLAT,
    MAGICAL_DAMAGE_PERCENT,

    PROJECTILE_DAMAGE_FLAT,
    PROJECTILE_DAMAGE_PERCENT,

    /* Resistances */
    FIRE_RESIST_PERCENT,
    COLD_RESIST_PERCENT,
    LIGHTNING_RESIST_PERCENT,
    POISON_RESIST_PERCENT,
    PHYSICAL_RESIST_PERCENT,
    MAGICAL_RESIST_PERCENT,

    /* Critical */
    CRITICAL_STRIKE_CHANCE_PERCENT,
    CRITICAL_STRIKE_DAMAGE_PERCENT,

    /* Utility / Defense */
    DODGE_CHANCE_PERCENT,
    STABILITY_PERCENT,
    INCREASE_PARRY_WINDOW_FLAT,

    /* Misc */
    JUMPS_FLAT,
    RUN_SPEED_PERCENT
}
