package com.example.hyarpg.utils.affixes;

public enum StatType {

    /* Primary Resources */
    LIFE_FLAT,
    LIFE_PERCENT,

    LIFE_REGEN_FLAT,
    LIFE_REGEN_PERCENT,

    STAMINA_FLAT,
    STAMINA_PERCENT,

    STAMINA_REGEN_FLAT,
    STAMINA_REGEN_PERCENT,

    MANA_FLAT,
    MANA_PERCENT,

    MANA_REGEN_FLAT,
    MANA_REGEN_PERCENT,

    /* Damage */
    FIRE_DAMAGE_FLAT,
    FIRE_DAMAGE_PERCENT,

    ICE_DAMAGE_FLAT,
    ICE_DAMAGE_PERCENT,

    LIGHTNING_DAMAGE_FLAT,
    LIGHTNING_DAMAGE_PERCENT,

    POISON_DAMAGE_FLAT,
    POISON_DAMAGE_PERCENT,

    PHYSICAL_DAMAGE_FLAT,
    PHYSICAL_DAMAGE_PERCENT,

    MAGIC_DAMAGE_FLAT,
    MAGIC_DAMAGE_PERCENT,

    /* Weapon Damages */
    AXE_DAMAGE_PERCENT,
    BATTLEAXE_DAMAGE_PERCENT,
    CLUB_DAMAGE_PERCENT,
    DAGGERS_DAMAGE_PERCENT,
    KUNAI_DAMAGE_PERCENT,
    LONGSWORD_DAMAGE_PERCENT,
    MACE_DAMAGE_PERCENT,
    SHORTBOW_DAMAGE_PERCENT,
    CROSSBOW_DAMAGE_PERCENT,
    SWORD_DAMAGE_PERCENT,
    STAFF_DAMAGE_PERCENT,
    WAND_DAMAGE_PERCENT,

    /* Weapon Specific */
    SHIELD_STABILITY_PERCENT,

    // Main Hand Flat Damages
    MAIN_HAND_FIRE_DAMAGE_FLAT,
    MAIN_HAND_ICE_DAMAGE_FLAT,
    MAIN_HAND_LIGHTNING_DAMAGE_FLAT,
    MAIN_HAND_POISON_DAMAGE_FLAT,
    MAIN_HAND_PHYSICAL_DAMAGE_FLAT,
    MAIN_HAND_MAGIC_DAMAGE_FLAT,

    // Off-Hand Damage Conversion Stats (hidden, does not roll in pools, used on components)
    OFF_HAND_FIRE_DAMAGE_FLAT,
    OFF_HAND_ICE_DAMAGE_FLAT,
    OFF_HAND_LIGHTNING_DAMAGE_FLAT,
    OFF_HAND_POISON_DAMAGE_FLAT,
    OFF_HAND_PHYSICAL_DAMAGE_FLAT,
    OFF_HAND_MAGIC_DAMAGE_FLAT,

    /* Resistances */
    FIRE_RESIST_PERCENT,
    ICE_RESIST_PERCENT,
    LIGHTNING_RESIST_PERCENT,
    POISON_RESIST_PERCENT,
    PHYSICAL_RESIST_PERCENT,
    MAGIC_RESIST_PERCENT,
    ELEMENTAL_RESIST_PERCENT,
    FALL_RESIST_PERCENT,

    /* Critical */
    CRITICAL_STRIKE_CHANCE_PERCENT,
    CRITICAL_STRIKE_DAMAGE_PERCENT,

    /* Utility / Defense */
    DODGE_CHANCE_PERCENT,
    STABILITY_PERCENT,
    PARRY_WINDOW_FLAT,
    BARRIER_ON_BLOCK,

    /* Ammo Modifiers */
    AMMO_FLAT,
    AMMO_REGEN_PERCENT,

    /* Leech Modifiers */
    LIFE_LEECH_PERCENT,
    MANA_LEECH_PERCENT,
    STAMINA_LEECH_PERCENT,

    /* Damage Taken From Modifiers */
    DAMAGE_TAKEN_FROM_MANA_PERCENT,
    DAMAGE_TAKEN_FROM_STAMINA_PERCENT,

    /* Misc */
    RUN_SPEED_PERCENT,
    APPLY_ASSASSIN_MARK_FLAT
}
