package com.example.hyarpg.utils.affixes;

public enum StatType {

    /* Primary Resources */
    LIFE_FLAT,
    LIFE_PERCENT,

    LIFE_REGEN_FLAT,
    LIFE_REGEN_PERCENT,

    STAMINA_FLAT,
    STAMINA_PERCENT,

    STAMINA_REGEN_FLAT,
    STAMINA_REGEN_PERCENT,

    MANA_FLAT,
    MANA_PERCENT,

    MANA_REGEN_FLAT,
    MANA_REGEN_PERCENT,

    /* Damage */
    FIRE_DAMAGE_FLAT,
    FIRE_DAMAGE_PERCENT,

    ICE_DAMAGE_FLAT,
    ICE_DAMAGE_PERCENT,

    LIGHTNING_DAMAGE_FLAT,
    LIGHTNING_DAMAGE_PERCENT,

    POISON_DAMAGE_FLAT,
    POISON_DAMAGE_PERCENT,

    PHYSICAL_DAMAGE_FLAT,
    PHYSICAL_DAMAGE_PERCENT,

    MAGIC_DAMAGE_FLAT,
    MAGIC_DAMAGE_PERCENT,

    /* Weapon Damages */
    AXE_DAMAGE_PERCENT,
    BATTLEAXE_DAMAGE_PERCENT,
    CLUB_DAMAGE_PERCENT,
    DAGGERS_DAMAGE_PERCENT,
    KUNAI_DAMAGE_PERCENT,
    LONGSWORD_DAMAGE_PERCENT,
    MACE_DAMAGE_PERCENT,
    SHORTBOW_DAMAGE_PERCENT,
    SWORD_DAMAGE_PERCENT,

    /* Weapon Specific */
    SHIELD_STABILITY_PERCENT,

    /* Resistances */
    FIRE_RESIST_PERCENT,
    ICE_RESIST_PERCENT,
    LIGHTNING_RESIST_PERCENT,
    POISON_RESIST_PERCENT,
    PHYSICAL_RESIST_PERCENT,
    MAGIC_RESIST_PERCENT,
    ELEMENTAL_RESIST_PERCENT,

    /* Critical */
    CRITICAL_STRIKE_CHANCE_PERCENT,
    CRITICAL_STRIKE_DAMAGE_PERCENT,

    /* Utility / Defense */
    DODGE_CHANCE_PERCENT,
    STABILITY_PERCENT,
    PARRY_WINDOW_FLAT,
    BARRIER_ON_BLOCK,

    /* Misc */
    RUN_SPEED_PERCENT
}
